
export interface FeaturedJobsProps  {
    jobTitle?: string,
    companyName?: string,
    jobDescription?: string,
    jobType?: string,
    jobLocation?: string,
    jobSkills?: string,
    education?: string,
    jobSalary?: string,
    jobOverview?: string,
    jobResponsibility?: string,
    key?: string,
    isRemote?: boolean
    roleLevel?: string,
    industry?: string,

}
export const getFeaturedJobs = (): FeaturedJobsProps[] => [
    {
        key: "admin-work_dataAnalytics",
        jobTitle: "Data Analytics",
        companyName: "Nayasty Technology Consult",
        jobDescription: "Analyze and interpret data to provide insights that help improve business processes and decision-making. The role involves working with large datasets, cleaning data, and reporting findings.",
        jobType: "Remote",
        jobLocation: "Koforidua, Two Streams",
        jobSkills: "Python, Power BI, SQL, R, Tableau, SAS, SPSS, Machine learning, Data mining",
        education: "A bachelor's degree in a field such as statistics, mathematics, computer science, or business is required.",
        jobSalary: "1,000 - 3,000 cedis per month",
        jobOverview: "Work remotely to analyze business data and provide actionable insights to various teams.",
        jobResponsibility: "Collect, clean, and analyze data; generate reports; maintain databases; and collaborate with senior analysts.",
        isRemote: true,
        roleLevel: "Entry Level",
        industry: "Technology"
    },
    {
        key: "admin-work_pharmacist",
        jobTitle: "Pharmacist",
        companyName: "Bedicta Pharmaceutical Shop",
        jobDescription: "Responsible for overseeing medication management, ensuring compliance with healthcare regulations, and educating patients about proper medication use.",
        jobType: "On-site",
        jobLocation: "Koforidua, Adweso",
        jobSkills: "Clinical knowledge, attention to detail, communication skills, customer service, management skills",
        education: "Bachelor's Degree in Pharmacy (B.Pharm), typically a 4-year program that covers fundamental pharmacy concepts, including pharmacology, chemistry, and medical ethics.",
        jobSalary: "4,000 - 10,000 cedis per month",
        jobOverview: "Ensure safe and effective medication use in collaboration with healthcare teams.",
        jobResponsibility: "Manage medication inventory, ensure compliance with pharmaceutical regulations, and educate patients on medication safety.",
        isRemote: false,
        roleLevel: "Senior Level",
        industry: "Healthcare"
    },
    {
        key: "hospi-work_cateringService",
        jobTitle: "Catering Service",
        companyName: "Doreen & Joseph Catering Service",
        jobDescription: "Responsible for preparing and baking high-quality pastries, cakes, and desserts, while managing customer orders and ensuring timely delivery.",
        jobType: "On-site",
        jobLocation: "Koforidua, Effiduase",
        jobSkills: "Culinary Skills, Food Safety and Sanitation, Customer Service, Time Management, Teamwork, Creativity",
        education: "High School Diploma or Equivalent, with Vocational Training in home economics or culinary arts.",
        jobSalary: "2,000 - 6,000 cedis per month",
        jobOverview: "Prepare baked goods for events while ensuring customer satisfaction and timely service.",
        jobResponsibility: "Prepare and bake high-quality pastries, manage customer orders, and ensure exceptional service delivery.",
        isRemote: false,
        roleLevel: "Mid-Level",
        industry: "Hospitality"
    },
    {
        key: "gasoline_work_gasAttendant",
        jobTitle: "Gas Attendant/ Gas Jockey",
        companyName: "Goil PLC",
        jobDescription: "Responsible for dispensing gasoline, handling customer payments, and ensuring the safety of gas stations.",
        jobType: "On-site",
        jobLocation: "Koforidua, Galaway Junction",
        jobSkills: "Safety Awareness, Physical Stamina, Attention to Detail, Basic Math Skills, Customer Service, Communication Skills",
        education: "High School Diploma or Equivalent: basic knowledge for handling cash, understanding safety protocols, and providing customer service.",
        jobSalary: "1,000 - 2,500 cedis per month",
        jobOverview: "Serve customers by dispensing gasoline and ensuring safety at the gas station.",
        jobResponsibility: "Dispense gasoline, handle customer payments, and ensure gas station safety protocols are followed.",
        isRemote: false,
        roleLevel: "Entry Level",
        industry: "Energy"
    },
    {
        key: "barKeeper-work_barAttendant",
        jobTitle: "Junior Service Barman/ Barmaid",
        companyName: "Lumen Bar & Grill",
        jobDescription: "Serve customers by preparing drinks, managing orders, and ensuring customer satisfaction in compliance with alcohol laws.",
        jobType: "On-site",
        jobLocation: "Koforidua, Adweso",
        jobSkills: "Memory and Multitasking, Basic Math Skills, Physical Stamina, Communication Skills, Customer Service, Knowledge of Alcohol Laws",
        education: "High School Diploma, Certifications from Bartending School: Knowledge in drink mixing, customer service, and bar operations.",
        jobSalary: "1,500 - 3,000 cedis per month",
        jobOverview: "Serve drinks and manage bar operations while ensuring customer satisfaction.",
        jobResponsibility: "Prepare and serve drinks, manage customer orders, and ensure compliance with alcohol regulations.",
        isRemote: false,
        roleLevel: "Junior Level",
        industry: "Hospitality"
    }
]