interface Country {
    country_name: string;
    country_code: string;
}

export const countries: Country[] = [
    { country_name: "Afghanistan", country_code: "+93" },
    { country_name: "Albania", country_code: "+355" },
    { country_name: "Algeria", country_code: "+213" },
    { country_name: "Andorra", country_code: "+376" },
    { country_name: "Angola", country_code: "+244" },
    { country_name: "Argentina", country_code: "+54" },
    { country_name: "Armenia", country_code: "+374" },
    { country_name: "Australia", country_code: "+61" },
    { country_name: "Austria", country_code: "+43" },
    { country_name: "Azerbaijan", country_code: "+994" },
    { country_name: "Bahamas", country_code: "+1-242" },
    { country_name: "Bahrain", country_code: "+973" },
    { country_name: "Bangladesh", country_code: "+880" },
    { country_name: "Barbados", country_code: "+1-246" },
    { country_name: "Belarus", country_code: "+375" },
    { country_name: "Belgium", country_code: "+32" },
    { country_name: "Belize", country_code: "+501" },
    { country_name: "Benin", country_code: "+229" },
    { country_name: "Bhutan", country_code: "+975" },
    { country_name: "Bolivia", country_code: "+591" },
    { country_name: "Bosnia and Herzegovina", country_code: "+387" },
    { country_name: "Botswana", country_code: "+267" },
    { country_name: "Brazil", country_code: "+55" },
    { country_name: "Brunei", country_code: "+673" },
    { country_name: "Bulgaria", country_code: "+359" },
    { country_name: "Burkina Faso", country_code: "+226" },
    { country_name: "Burundi", country_code: "+257" },
    { country_name: "Cambodia", country_code: "+855" },
    { country_name: "Cameroon", country_code: "+237" },
    { country_name: "Canada", country_code: "+1" },
    { country_name: "Cape Verde", country_code: "+238" },
    { country_name: "Central African Republic", country_code: "+236" },
    { country_name: "Chad", country_code: "+235" },
    { country_name: "Chile", country_code: "+56" },
    { country_name: "China", country_code: "+86" },
    { country_name: "Colombia", country_code: "+57" },
    { country_name: "Comoros", country_code: "+269" },
    { country_name: "Congo", country_code: "+242" },
    { country_name: "Congo, Democratic Republic of the", country_code: "+243" },
    { country_name: "Costa Rica", country_code: "+506" },
    { country_name: "Croatia", country_code: "+385" },
    { country_name: "Cuba", country_code: "+53" },
    { country_name: "Cyprus", country_code: "+357" },
    { country_name: "Czech Republic", country_code: "+420" },
    { country_name: "Denmark", country_code: "+45" },
    { country_name: "Djibouti", country_code: "+253" },
    { country_name: "Dominica", country_code: "+1-767" },
    { country_name: "Dominican Republic", country_code: "+1-809" },
    { country_name: "Ecuador", country_code: "+593" },
    { country_name: "Egypt", country_code: "+20" },
    { country_name: "El Salvador", country_code: "+503" },
    { country_name: "Equatorial Guinea", country_code: "+240" },
    { country_name: "Eritrea", country_code: "+291" },
    { country_name: "Estonia", country_code: "+372" },
    { country_name: "Eswatini", country_code: "+268" },
    { country_name: "Ethiopia", country_code: "+251" },
    { country_name: "Fiji", country_code: "+679" },
    { country_name: "Finland", country_code: "+358" },
    { country_name: "France", country_code: "+33" },
    { country_name: "Gabon", country_code: "+241" },
    { country_name: "Gambia", country_code: "+220" },
    { country_name: "Georgia", country_code: "+995" },
    { country_name: "Germany", country_code: "+49" },
    { country_name: "Ghana", country_code: "+233" },
    { country_name: "Greece", country_code: "+30" },
    { country_name: "Grenada", country_code: "+1-473" },
    { country_name: "Guatemala", country_code: "+502" },
    { country_name: "Guinea", country_code: "+224" },
    { country_name: "Guinea-Bissau", country_code: "+245" },
    { country_name: "Guyana", country_code: "+592" },
    { country_name: "Haiti", country_code: "+509" },
    { country_name: "Honduras", country_code: "+504" },
    { country_name: "Hungary", country_code: "+36" },
    { country_name: "Iceland", country_code: "+354" },
    { country_name: "India", country_code: "+91" },
    { country_name: "Indonesia", country_code: "+62" },
    { country_name: "Iran", country_code: "+98" },
    { country_name: "Iraq", country_code: "+964" },
    { country_name: "Ireland", country_code: "+353" },
    { country_name: "Israel", country_code: "+972" },
    { country_name: "Italy", country_code: "+39" },
    { country_name: "Jamaica", country_code: "+1-876" },
    { country_name: "Japan", country_code: "+81" },
    { country_name: "Jordan", country_code: "+962" },
    { country_name: "Kazakhstan", country_code: "+7" },
    { country_name: "Kenya", country_code: "+254" },
    { country_name: "Kiribati", country_code: "+686" },
    { country_name: "Kuwait", country_code: "+965" },
    { country_name: "Kyrgyzstan", country_code: "+996" },
    { country_name: "Laos", country_code: "+856" },
    { country_name: "Latvia", country_code: "+371" },
    { country_name: "Lebanon", country_code: "+961" },
    { country_name: "Lesotho", country_code: "+266" },
    { country_name: "Liberia", country_code: "+231" },
    { country_name: "Libya", country_code: "+218" },
    { country_name: "Liechtenstein", country_code: "+423" },
    { country_name: "Lithuania", country_code: "+370" },
    { country_name: "Luxembourg", country_code: "+352" },
    { country_name: "Madagascar", country_code: "+261" },
    { country_name: "Malawi", country_code: "+265" },
    { country_name: "Malaysia", country_code: "+60" },
    { country_name: "Maldives", country_code: "+960" },
    { country_name: "Mali", country_code: "+223" },
    { country_name: "Malta", country_code: "+356" },
    { country_name: "Marshall Islands", country_code: "+692" },
    { country_name: "Mauritania", country_code: "+222" },
    { country_name: "Mauritius", country_code: "+230" },
    { country_name: "Mexico", country_code: "+52" },
    { country_name: "Micronesia", country_code: "+691" },
    { country_name: "Moldova", country_code: "+373" },
    { country_name: "Monaco", country_code: "+377" },
    { country_name: "Mongolia", country_code: "+976" },
    { country_name: "Montenegro", country_code: "+382" },
    { country_name: "Morocco", country_code: "+212" },
    { country_name: "Mozambique", country_code: "+258" },
    { country_name: "Myanmar", country_code: "+95" },
    { country_name: "Namibia", country_code: "+264" },
    { country_name: "Nauru", country_code: "+674" },
    { country_name: "Nepal", country_code: "+977" },
    { country_name: "Netherlands", country_code: "+31" },
    { country_name: "New Zealand", country_code: "+64" },
    { country_name: "Nicaragua", country_code: "+505" },
    { country_name: "Niger", country_code: "+227" },
    { country_name: "Nigeria", country_code: "+234" },
    { country_name: "North Macedonia", country_code: "+389" },
    { country_name: "Norway", country_code: "+47" },
    { country_name: "Oman", country_code: "+968" },
    { country_name: "Pakistan", country_code: "+92" },
    { country_name: "Palau", country_code: "+680" },
    { country_name: "Panama", country_code: "+507" },
    { country_name: "Papua New Guinea", country_code: "+675" },
    { country_name: "Paraguay", country_code: "+595" },
    { country_name: "Peru", country_code: "+51" },
    { country_name: "Philippines", country_code: "+63" },
    { country_name: "Poland", country_code: "+48" },
    { country_name: "Portugal", country_code: "+351" },
    { country_name: "Qatar", country_code: "+974" },
    { country_name: "Romania", country_code: "+40" },
    { country_name: "Russia", country_code: "+7" },
    { country_name: "Rwanda", country_code: "+250" },
    { country_name: "Saint Kitts and Nevis", country_code: "+1-869" },
    { country_name: "Saint Lucia", country_code: "+1-758" },
    { country_name: "Saint Vincent and the Grenadines", country_code: "+1-784" },
    { country_name: "Samoa", country_code: "+685" },
    { country_name: "San Marino", country_code: "+378" },
    { country_name: "Saudi Arabia", country_code: "+966" },
    { country_name: "Senegal", country_code: "+221" },
    { country_name: "Serbia", country_code: "+381" },
    { country_name: "Seychelles", country_code: "+248" },
    { country_name: "Sierra Leone", country_code: "+232" },
    { country_name: "Singapore", country_code: "+65" },
    { country_name: "Slovakia", country_code: "+421" },
    { country_name: "Slovenia", country_code: "+386" },
    { country_name: "Solomon Islands", country_code: "+677" },
    { country_name: "Somalia", country_code: "+252" },
    { country_name: "South Africa", country_code: "+27" },
    { country_name: "South Sudan", country_code: "+211" },
    { country_name: "Spain", country_code: "+34" },
    { country_name: "Sri Lanka", country_code: "+94" },
    { country_name: "Sudan", country_code: "+249" },
    { country_name: "Suriname", country_code: "+597" },
    { country_name: "Sweden", country_code: "+46" },
    { country_name: "Switzerland", country_code: "+41" },
    { country_name: "Syria", country_code: "+963" },
    { country_name: "Taiwan", country_code: "+886" },
    { country_name: "Tajikistan", country_code: "+992" },
    { country_name: "Tanzania", country_code: "+255" },
    { country_name: "Thailand", country_code: "+66" },
    { country_name: "Timor-Leste", country_code: "+670" },
    { country_name: "Togo", country_code: "+228" },
    { country_name: "Tonga", country_code: "+676" },
    { country_name: "Trinidad and Tobago", country_code: "+1-868" },
    { country_name: "Tunisia", country_code: "+216" },
    { country_name: "Turkey", country_code: "+90" },
    { country_name: "Turkmenistan", country_code: "+993" },
    { country_name: "Tuvalu", country_code: "+688" },
    { country_name: "Uganda", country_code: "+256" },
    { country_name: "Ukraine", country_code: "+380" },
    { country_name: "United Arab Emirates", country_code: "+971" },
    { country_name: "United Kingdom", country_code: "+44" },
    { country_name: "United States", country_code: "+1" },
    { country_name: "Uruguay", country_code: "+598" },
    { country_name: "Uzbekistan", country_code: "+998" },
    { country_name: "Vanuatu", country_code: "+678" },
    { country_name: "Vatican City", country_code: "+379" },
    { country_name: "Venezuela", country_code: "+58" },
    { country_name: "Vietnam", country_code: "+84" },
    { country_name: "Yemen", country_code: "+967" },
    { country_name: "Zambia", country_code: "+260" },
    { country_name: "Zimbabwe", country_code: "+263" }
];
